// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9Br6mj0uAFd91uqSHASK1GgHUJR59ZE',
    appId: '1:560491690614:android:63f748c8fda47a9ef33d57',
    messagingSenderId: '560491690614',
    projectId: 'loginandsignupdetails-29eb5',
    databaseURL: 'https://loginandsignupdetails-29eb5-default-rtdb.firebaseio.com',
    storageBucket: 'loginandsignupdetails-29eb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8SRXdC-HLejb8l8hiKh3jaLNh5TNkgBM',
    appId: '1:560491690614:ios:72d791c3b326a80ff33d57',
    messagingSenderId: '560491690614',
    projectId: 'loginandsignupdetails-29eb5',
    databaseURL: 'https://loginandsignupdetails-29eb5-default-rtdb.firebaseio.com',
    storageBucket: 'loginandsignupdetails-29eb5.appspot.com',
    iosBundleId: 'com.example.meals',
  );
}
